### ISSUE TITLE
Fix coveralls badge

### ISSUE THREAD

**Issue by omphalos** [kadtools/kad-localstorage#2]
@gordonwritescode The coveralls badge points at my old repo.  I think we need a coveralls account for kadtools.  I think (?) you need to make it, not myself.  Would you mind doing so?  If you do then I think I ought to be able to fix the badge link and run a travis build and, fingers crossed, everything will "just work".

**Comment by gordonwritescode** [comment]
Sure thing, I'll take a look and also see what I need to do to make sure you don't run into access problems like this.

**Comment by gordonwritescode** [comment]
Looks like it's already set up? Should just be able to point the image.

https://coveralls.io/github/kadtools/kad-localstorage

**Comment by omphalos** [comment]
It works, thanks!
