### ISSUE TITLE
Webpack crash

### ISSUE THREAD

**Issue by MaxSvargal** [kadtools/kad-localstorage#3]
On line https://github.com/kadtools/kad-localstorage/blob/master/kad-localstorage.js#L1
webpack crashed with
```
ERROR in ./~/kad-localstorage/kad-localstorage.js
Module parse failed: ~/node_modules/kad-localstorage/kad-localstorage.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (1:0)
```

**Comment by omphalos** [comment]
@MaxSvargal thanks for reporting this.  I removed the `#` at the beginning of the file.  I believe webpack should be happy now.  Please let me know if it isn't.

**Comment by MaxSvargal** [comment]
@omphalos it's ok, thank you!
